name: Build Main

on:
  push:
    branches:
      - main
      - release-prep
    tags:
      - camel-catalog-mcp-*


env:
  PROJECTS: ${{ github.workspace }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build
      run: |
        mvn -B package
    - name: Login to Container Registry
      uses: docker/login-action@v3
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_PASSWORD }}
    - name: Publish
      run: |
        mvn -B install \
          -Dquarkus.container-image.build=true \
          -Dquarkus.container-image.push=true \
          -Dquarkus.container-image.additional-tags=${{ github.ref_name }}